http{
	client_max_body_size 1G;
	root ./var/www/html;
	autoindex on;
	server{
		listen 9001;
		server_name localhost;
		location /
    	{
		    limit_except GET POST {
			    deny all;
			}
		}

		location /cgi {
			index index.html;
			limit_except GET POST {
				deny all;
			}
			error_page 404 /error_pages/404.html;
			error_page 500 /error_pages/500.html;
			error_page 504 /error_pages/504.html;
		}

		location /tic_tac_toe {
			root ./var/www/html/cgi;
			index index.py;
			limit_except GET POST {
				deny all;
			}
			fastcgi_pass /usr/bin/python3;
			fastcgi_extension py;
		}

		location /php {
			root ./var/www/html/cgi;
			index index.php;
			limit_except GET POST {
				deny all;
			}
			fastcgi_pass /usr/bin/php-cgi;
			fastcgi_extension php;
		}

		location /python {
			root ./var/www/html/cgi;
			index index.py;
			limit_except GET POST {
				deny all;
			}
			fastcgi_pass /usr/bin/python3;
			fastcgi_extension py;
		}

		location /uploads {
			web_dav on;
			limit_except GET POST DELETE {
		        deny all;
			}
		}

		location /method/get {
			web_dav on;
			limit_except GET {
				deny all;
			}
		}

		location /method/post {
			web_dav on;
			limit_except POST {
				deny all;
			}
		}

		location /method/delete {
			web_dav on;
			limit_except DELETE {
				deny all;
			}
		}

		location /directory {
			root ./var/www/html;
			autoindex on;
		}

		location /directory/sub_directory {
			root ./var/www/html;
			autoindex on;
		}

		location /directory/sub_directory_off {
			root ./var/www/html;
			autoindex off;
		}

		location /directory/sub_directory_off/sub_sub_directory {
			root ./var/www/html;
			autoindex on;
		}

		location /directory/sub_directory/sub_sub_directory {
			root ./var/www/html;
			autoindex on;
		}

		location /directory/sub_directory/sub_sub_directory_off {
			root ./var/www/html;
			autoindex off;
		}

		location /coffee {
			return 418;
		}

		location /200 {
			return 200;
		}

		location /200t {
			return 200 OK;
		}

		location /301 {
			return 301;
		}

		location /301t {
			return 301 http://localhost:8090;
		}

		location /301i {
			return 301 http://google.com;
		}

		location /404 {
			return 404;
		}

		location /404t {
			return 404 ERROR;
		}

		location /500 {
			return 500;
		}

		location /500t {
			return 500 INTERNAL;
		}

		location /599 {
			return 599;
		}

		location /599t {
			return 599 XXX;
		}

		location /1b {
			root ./var/www/html/method/limit;
			web_dav on;
			client_max_body_size 1B;
			limit_except GET POST DELETE {
				deny all;
			}
		}

		location /5b {
			root ./var/www/html/method/limit;
			web_dav on;
			client_max_body_size 5B;
			limit_except GET POST DELETE {
				deny all;
			}
		}

		location /10b {
			root ./var/www/html/method/limit;
			web_dav on;
			client_max_body_size 10B;
			limit_except GET POST DELETE {
				deny all;
			}
		}

		location /bad_getway {
			fastcgi_pass /;
		}
	}
	server {
		listen 9000;
		server_name royalbox.com.br www.royalbox.com.br;
		root ./var/www/html/static_site;
	}
	server {
		listen 9002;
		server_name localhost;
		root ./var/www/html;
		location / {
			fastcgi_pass /usr/bin/bash;
			fastcgi_extension sh;
			limit_except GET POST {
				deny all;
			}
		}
	}
}
