#ifndef CODE_HPP
#define CODE_HPP

#include <string>

namespace code {

	enum {
		BAD_REQUEST = 400,
		UNAUTHORIZED = 401,
		FORBBIDEN = 403,
		NOT_FOUND = 404,
		METHOD_NOT_ALLOWED = 405,
		LENGTH_REQUIRED = 411,
		PAYLOAD_TOO_LARGE = 413,
		UNSUPORTED_MEDIA_TYPE = 415,
		UNPROCESSABLE_CONTENT = 422,
		INTERNAL_SERVER_ERROR = 500,
		GATEWAY_TIMEOUT = 504,
		HTTP_VERSION_NOT_SUPPORTED = 505
	};

}

#endif /* CODE_HPP */
