name: Build

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: ["main", "develop"]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          make