name: Test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Run tests
        run: |
          make test